### ISSUE TITLE
M2020 # SyntaxError: invalid syntax # 

### ISSUE THREAD

**Issue by daythatidie** [JakobJK/modelChecker#21]
Maya 2020, Python 3.12

```
modelChecker_UI.UI.show_UI()
# Error: invalid syntax
# Traceback (most recent call last):
#   File "<maya console>", line 1, in <module>
#   File "C:/Users/User/Documents/maya/2020/scripts\modelChecker\modelChecker_UI.py", line 324
#     html += f"{key}: {metadata[key]}<br>"
#                                                                ^
# SyntaxError: invalid syntax # 
```

**Comment by daythatidie** [comment]
Looks like Maya 2020 does not support python f-strings. Changing to concatenation solved the problem.

**Comment by JakobJK** [comment]
Absolutely! If you look at the latest code there are no f-strings in the repo anymore, so you might have an older version of the modelChecker.
